"""Строки сайта: ru, en, vi"""

SITE_STRINGS = {
    "ru": {
        "nav_create": "Создать",
        "nav_profile": "Профиль",
        "nav_login": "Вход",
        "nav_register": "Регистрация",
        "nav_logout": "Выход",
        "nav_admin": "Админка",
        "nav_balance": "Пополнить",
        "footer_support": "Техподдержка",
        "footer_instructions": "Инструкция",
        "footer_terms": "Пользовательское соглашение",
        "page_login": "Вход",
        "page_register": "Регистрация",
        "page_profile": "Профиль",
        "page_balance": "Пополнение баланса",
        "page_support": "Техподдержка",
        "page_instructions": "Инструкция",
        "page_terms": "Пользовательское соглашение",
        "login_email": "Email",
        "login_password": "Пароль",
        "login_submit": "Войти",
        "login_no_account": "Нет аккаунта?",
        "register_submit": "Зарегистрироваться",
        "register_repeat_password": "Повторите пароль",
        "register_has_account": "Уже есть аккаунт?",
        "profile_email": "Email",
        "profile_balance": "Баланс",
        "profile_lang": "Язык",
        "profile_history": "История генераций",
        "profile_no_history": "Пока нет генераций",
        "profile_date": "Дата",
        "profile_category": "Категория",
        "profile_result": "Результат",
        "profile_open": "Открыть",
        "balance_title": "Пополнение баланса",
        "balance_current": "Ваш баланс",
        "balance_price": "Стоимость 1 генерации",
        "balance_wholesale": "ОПТОМ от 10 000 руб — цена 15 руб за фото.",
        "balance_contact": "Для пополнения напишите администратору:",
        "support_title": "Техподдержка",
        "support_text": "По всем вопросам обращайтесь:",
        "welcome_title": "Генерация изображений",
        "welcome_subtitle": "Выберите категорию и следуйте шагам для создания изображения",
        "welcome_step1": "1. Выберите категорию",
        "welcome_step2": "2. Выберите модель",
        "welcome_step3": "3. Загрузите фото товара",
        "welcome_step3a": "3. Загрузите фото фона или сцены",
        "welcome_step4": "4. Загрузите фото товара",
        "welcome_upload_product": "Загрузите фото товара",
        "welcome_upload_bg": "Фото интерьера, локации или фона, куда будет помещён товар",
        "welcome_upload_product_on_bg": "Фото товара, который нужно разместить на выбранном фоне",
        "welcome_storefront_hint": "Фон возьмём из выбранной модели. Загрузите фото товара",
        "welcome_back": "Назад",
        "welcome_next": "Далее",
        "welcome_format": "Формат фото",
        "welcome_generate": "Генерация",
        "welcome_cost": "Стоимость",
        "welcome_generate_btn": "Сгенерировать",
        "welcome_done": "Готово!",
        "welcome_create_more": "Создать ещё",
        "welcome_model": "Модель",
        "terms_default": "Пользовательское соглашение. Администратор может настроить текст в разделе «Настройки» админ-панели.",
    },
    "en": {
        "nav_create": "Create",
        "nav_profile": "Profile",
        "nav_login": "Login",
        "nav_register": "Register",
        "nav_logout": "Logout",
        "nav_admin": "Admin",
        "nav_balance": "Top up",
        "footer_support": "Support",
        "footer_instructions": "Instructions",
        "footer_terms": "Terms of Service",
        "page_login": "Login",
        "page_register": "Register",
        "page_profile": "Profile",
        "page_balance": "Top up Balance",
        "page_support": "Support",
        "page_instructions": "Instructions",
        "page_terms": "Terms of Service",
        "login_email": "Email",
        "login_password": "Password",
        "login_submit": "Log in",
        "login_no_account": "No account?",
        "register_submit": "Register",
        "register_repeat_password": "Repeat password",
        "register_has_account": "Already have an account?",
        "profile_email": "Email",
        "profile_balance": "Balance",
        "profile_lang": "Language",
        "profile_history": "Generation history",
        "profile_no_history": "No generations yet",
        "profile_date": "Date",
        "profile_category": "Category",
        "profile_result": "Result",
        "profile_open": "Open",
        "balance_title": "Top up Balance",
        "balance_current": "Your balance",
        "balance_price": "1 generation cost",
        "balance_wholesale": "Wholesale from 10,000 rub — 15 rub per photo.",
        "balance_contact": "To top up, contact the administrator:",
        "support_title": "Support",
        "support_text": "For any questions, contact:",
        "welcome_title": "Image Generation",
        "welcome_subtitle": "Choose a category and follow the steps to create an image",
        "welcome_step1": "1. Choose category",
        "welcome_step2": "2. Choose model",
        "welcome_step3": "3. Upload product photo",
        "welcome_step3a": "3. Upload background or scene photo",
        "welcome_step4": "4. Upload product photo",
        "welcome_upload_product": "Upload product photo",
        "welcome_upload_bg": "Interior, location or background photo where the product will be placed",
        "welcome_upload_product_on_bg": "Product photo to place on the selected background",
        "welcome_storefront_hint": "Background from selected model. Upload product photo",
        "welcome_back": "Back",
        "welcome_next": "Next",
        "welcome_format": "Photo format",
        "welcome_generate": "Generation",
        "welcome_cost": "Cost",
        "welcome_generate_btn": "Generate",
        "welcome_done": "Done!",
        "welcome_create_more": "Create more",
        "welcome_model": "Model",
        "terms_default": "Terms of Service. Administrator can configure the text in the Settings section of the admin panel.",
    },
    "vi": {
        "nav_create": "Tạo",
        "nav_profile": "Hồ sơ",
        "nav_login": "Đăng nhập",
        "nav_register": "Đăng ký",
        "nav_logout": "Đăng xuất",
        "nav_admin": "Quản trị",
        "nav_balance": "Nạp tiền",
        "footer_support": "Hỗ trợ",
        "footer_instructions": "Hướng dẫn",
        "footer_terms": "Điều khoản sử dụng",
        "page_login": "Đăng nhập",
        "page_register": "Đăng ký",
        "page_profile": "Hồ sơ",
        "page_balance": "Nạp tiền",
        "page_support": "Hỗ trợ",
        "page_instructions": "Hướng dẫn",
        "page_terms": "Điều khoản sử dụng",
        "login_email": "Email",
        "login_password": "Mật khẩu",
        "login_submit": "Đăng nhập",
        "login_no_account": "Chưa có tài khoản?",
        "register_submit": "Đăng ký",
        "register_repeat_password": "Nhập lại mật khẩu",
        "register_has_account": "Đã có tài khoản?",
        "profile_email": "Email",
        "profile_balance": "Số dư",
        "profile_lang": "Ngôn ngữ",
        "profile_history": "Lịch sử tạo ảnh",
        "profile_no_history": "Chưa có ảnh nào",
        "profile_date": "Ngày",
        "profile_category": "Danh mục",
        "profile_result": "Kết quả",
        "profile_open": "Mở",
        "balance_title": "Nạp tiền",
        "balance_current": "Số dư của bạn",
        "balance_price": "Giá 1 ảnh",
        "balance_wholesale": "MUA SỈ từ 10.000 rub — 15 rub/ảnh.",
        "balance_contact": "Để nạp tiền, liên hệ quản trị viên:",
        "support_title": "Hỗ trợ",
        "support_text": "Liên hệ với chúng tôi:",
        "welcome_title": "Tạo ảnh",
        "welcome_subtitle": "Chọn danh mục và làm theo các bước để tạo ảnh",
        "welcome_step1": "1. Chọn danh mục",
        "welcome_step2": "2. Chọn mẫu",
        "welcome_step3": "3. Tải ảnh sản phẩm",
        "welcome_step3a": "3. Tải ảnh nền hoặc hiện trường",
        "welcome_step4": "4. Tải ảnh sản phẩm",
        "welcome_upload_product": "Tải ảnh sản phẩm",
        "welcome_upload_bg": "Ảnh nội thất, địa điểm hoặc nền để đặt sản phẩm",
        "welcome_upload_product_on_bg": "Ảnh sản phẩm cần đặt trên nền đã chọn",
        "welcome_storefront_hint": "Nền từ mẫu đã chọn. Tải ảnh sản phẩm",
        "welcome_back": "Quay lại",
        "welcome_next": "Tiếp",
        "welcome_format": "Định dạng ảnh",
        "welcome_generate": "Tạo ảnh",
        "welcome_cost": "Chi phí",
        "welcome_generate_btn": "Tạo",
        "welcome_done": "Xong!",
        "welcome_create_more": "Tạo thêm",
        "welcome_model": "Mẫu",
        "terms_default": "Điều khoản sử dụng. Quản trị viên có thể cấu hình trong phần Cài đặt.",
    },
}


def get_site_string(key: str, lang: str) -> str:
    lang = lang or "ru"
    if lang not in SITE_STRINGS:
        lang = "ru"
    return SITE_STRINGS.get(lang, SITE_STRINGS["ru"]).get(key, key)
