STRINGS = {
    "ru": {
        "start_welcome": "Добро пожаловать в AI-ROOM! Выберите раздел:",
        "accept_terms": "Принять.",
        "subscribed": "Я подписался",
        "subscribe_channel": "Пожалуйста, подпишитесь на наш канал, чтобы использовать бота:",
        "menu_market": "Для маркетплейсов",
        "menu_profile": "Профиль",
        "menu_howto": "Инструкция",
        "menu_settings": "Настройки",
        "back_main": "⬅️ Назад в меню",
        "back": "⬅️ Назад",
        "lang_ru": "Русский",
        "lang_en": "English",
        "lang_vi": "Tiếng Việt",
        "select_lang": "Выберите язык:",
        "profile_info": "👤 Профиль\nID: {id}\nПодписка: {sub}\nОсталось генераций сегодня: {daily_rem}\n\nВыберите действие:",
        "sub_none": "Нет подписки",
        "sub_active": "{plan} (до {date})",
        "menu_subscription": "Подписка",
        "menu_history": "История генерации",
        "menu_referral": "Заработать с нами",
        "buy_plan": "Оформить подписку",
        "trial_info": "Вам доступен бесплатный пробный период: 1 день и 5 генераций!",
        "get_trial": "Получить пробный период",
        "marketplace_menu": "📦 Раздел для маркетплейсов:",
        "create_own_variant": "✨ Свой вариант",
        "upload_photo": "Загрузите фото. Отправьте их по одной или группой.",
        "enter_prompt": "Введите описание (до 1000 символов):",
        "select_format": "Выберите формат:",
        "history_title": "Последние 20 генераций:",
        "history_item": "PID: {pid}\nДата: {date}",
        "agreement": "Пользовательское соглашение",
        "how_to": "Как пользоваться ботом",
        "maintenance": "Ведутся технические работы. Пожалуйста, подождите.",
        "error_api": "Произошла ошибка при генерации. Попробуйте позже.",
        "rate_limit": "Слишком много запросов. Пожалуйста, подождите 20 секунд.",
        "create_normal_gen": "✨ ОБЫЧНАЯ ГЕНЕРАЦИЯ (до 3-х фото)",
        "create_photo": "Создать фото",
        "skip": "Пропустить",
        "select_body_type": "Выберите телосложение или введите числом:",
        "enter_height": "Введите рост модели в числах на пример 170.",
        "enter_age": "Введите возраст модели числом:",
        "select_pants_style": "Выберите тип кроя штанов:",
        "select_sleeve_length": "Выберите тип рукавов:",
        "select_garment_length": "Выберите длину изделия. Внимание! если ваш продукт Костюм 2-к, 3-к то длину можно не указывать.",
        "select_view": "Выберите ракурс фотографии:",
        "select_camera_dist": "Выберите ракурс (Дальний - Средний - Близкий):",
        "select_quality": "Выберите качество:",
        "gen_in_progress": "Генерация запущена. Пожалуйста, подождите...",
        "gen_success": "Ваше фото готово!",
        "gen_error": "Ошибка при генерации. Пожалуйста, попробуйте еще раз.",
        "quality_hd": "Стандарт (HD)",
        "quality_2k": "Премиум (2K)",
        "quality_4k": "Ультра (4K)",
        "view_front": "Спереди",
        "view_back": "Сзади",
        "view_side": "Сбоку",
        "cat_female": "👱‍♀️ Женская",
        "cat_male": "👨 Мужская",
        "cat_child": "🧒 Детская одежда",
        "cat_storefront": "🏬 Витринное фото",
        "cat_whitebg": "⚪ На белом фоне",
        "cat_random": "👕 Обувь и Одежда (Рандом)",
        "cat_own": "💃 Свой вариант МОДЕЛИ",
        "cat_own_variant": "🖼️ Свой вариант ФОНА",
        "cat_infographic_clothing": "🖼️ Инфогр: Одежда",
        "cat_infographic_other": "📦 Инфогр: Прочее",
        "pose_normal": "Обычная",
        "pose_unusual": "Нестандартная",
        "pose_vulgar": "Вульгарная",
        "dist_close": "Близкий",
        "dist_medium": "Средний",
        "dist_far": "Дальний",
        "load_min": "Минимальная",
        "load_med": "Средняя",
        "load_max": "Максимальная",
        "loc_outdoor": "На улице",
        "loc_indoor": "В помещении",
        "season_winter": "Зима",
        "season_summer": "Лето",
        "season_autumn": "Осень",
        "season_spring": "Весна",
        "holiday_wedding": "💍 Свадьба",
        "holiday_newyear": "🎄 Новый год",
        "holiday_bday": "🎂 День рождения",
        "holiday_march8": "💐 8 марта",
        "holiday_feb23": "🎖️ 23 Февраля",
        "holiday_may9": "9 мая",
        "holiday_momday": "👩‍👧 День матери",
        "holiday_teacherday": "👩‍🏫 День учителя",
        "holiday_russiaday": "🇷🇺 День России",
        "custom_variant": "✏️ Свой вариант",
        "gender_male": "👨 Мужской",
        "gender_female": "👱‍♀️ Женский",
        "gender_boy": "👦 Мальчик",
        "gender_girl": "👧 Девочка",
        "gender_neutral": "👫 Нейтральный",
        "gender_unisex": "👫 УНИСЕКС",
        "style_modern": "Современный",
        "style_simple": "Простой",
        "style_bright": "Яркий",
        "style_premium": "Премиальный",
        "style_child": "Детский",
        "style_tech": "Технологический",
        "style_natural": "Натуральный",
        "style_retro": "Ретро",
        "style_classic": "Классический",
        "style_atmos": "Атмосферный",
        "font_modern": "Современный",
        "font_serif": "С засечками",
        "font_sans": "Без засечек",
        "font_bold": "Жирный",
        "font_italic": "Курсив",
        "font_semibold": "Полужирный",
        "font_hand": "Рукописный",
        "font_decor": "Декоративный",
        "font_mono": "Моноширинный",
        "font_narrow": "Узкий",
        "font_tech": "Технологичный",
        "lang_ru_btn": "Русский",
        "lang_en_btn": "Английский",
        "lang_vi_btn": "Вьетнамский",
        "pants_relaxed": "Свободный крой",
        "pants_slim": "Зауженный",
        "pants_banana": "Бананы",
        "pants_flare_knee": "Клеш от колен",
        "pants_baggy": "Багги",
        "pants_mom": "Мом",
        "pants_straight": "Прямые",
        "sleeve_normal": "Обычный",
        "sleeve_long": "Длинные",
        "sleeve_three_quarter": "Три четверти",
        "sleeve_elbow": "До локтей",
        "sleeve_short": "Короткие",
        "sleeve_none": "Без рукав",
        "len_short_top": "Короткий топ",
        "len_regular_top": "Обычный топ",
        "len_to_waist": "До талии",
        "len_below_waist": "Ниже талии",
        "len_mid_thigh": "До середины бедра",
        "len_to_knees": "До колен",
        "len_below_knees": "Ниже колен",
        "len_midi": "Миди",
        "len_to_ankles": "До щиколоток",
        "len_to_floor": "До пола",
        "enter_product_name": "Введите название вашего продукта (до 75 символов):",
        "enter_loc_style": "Введите стиль локации / подтип (например: фотостудия в лофт стиле):",
        "enter_width": "Введите ширину (или пропустите):",
        "enter_height_dim": "Введите высоту (или пропустите):",
        "enter_length_dim": "Введите длину (или пропустите):",
        "enter_adv1": "Введите первое преимущество (до 180 символов):",
        "enter_adv2": "Введите второе преимущество (до 180 символов):",
        "enter_adv3": "Введите третье преимущество (до 180 символов):",
        "enter_additional": "Введите дополнительную информацию (до 100 символов):",
        "select_info_style": "Выберите стиль инфографики:",
        "select_font_type": "Выберите тип шрифта:",
        "select_info_lang": "Выберите язык инфографики:",
        "select_holiday": "Выберите праздник (или пропустите):",
        "select_season": "Выберите время года (или пропустите):",
        "select_gender": "К какому полу относится данный продукт:",
        "select_loc_group": "Выберите тип локации:",
        "select_location": "Выберите локацию:",
        "enter_custom_loc": "Введите ваш вариант локации (до 100 символов):",
        "enter_custom_holiday": "Введите ваш вариант праздника (до 30 символов):",
        "enter_custom_style": "Введите ваш вариант стиля (до 20 символов):",
        "enter_custom_font": "Введите ваш вариант шрифта (до 20 символов):",
        "enter_custom_lang": "Введите ваш вариант языка:",
        "upload_background": "Загрузите 1-ое фото, которое вам нравится:",
        "upload_product": "Загрузите фото товара:",
        "select_pose": "Выберите позу:",
        "enter_model_size": "Введите размер модели числом (или пропустите):",
        "child_category_notice": "Примечание: для детской категории промпты формируются отдельно.",
        "disclaimer": "Внимание! Результат может отличаться в зависимости от заданных параметров.",
        "model_label": "Модель",
        "presets_label": "Пресеты для одежды",
        "cloth_coat": "Куртка (Пальто)",
        "cloth_dress": "Платье",
        "cloth_shorts": "Шорты",
        "cloth_suit": "Костюм",
        "cloth_loungewear": "Домашняя одежда",
        "cloth_overall": "Комбинезон",
        "cloth_skirt": "Юбка",
        "cloth_shoes": "Обувь",
        "subcat_outerwear": "Верхняя одежда",
        "subcat_top": "Одежда для верха",
        "subcat_bottom": "Одежда для низа",
        "subcat_underwear": "Нижнее бельё",
        "subcat_sport": "Спортивная одежда",
        "subcat_sleepwear": "Одежда для сна",
        "subcat_swimwear": "Плавание",
        "subcat_accessories": "Аксессуары",
        "subcat_socks": "Носки",
        "subcat_dresses": "Платья и комбинезоны",
        "other": "Другое",
        "maintenance_alert": "🛠 Технические работы. Подписка будет продлена.",
        "disclaimer_text": "Текст: обратите внимание внешность или другие параметры могут отличаться в зависимости от заданных параметров.",
        "no_models_in_category_alert": "В этой категории пока нет моделей",
        "model_presets_title": "Прессеты для одежды\n\nМодель: {name} ({index}/{total})",
        "gender_presets_title": "Прессеты для {gender}\n\nМодель: {name} ({index}/{total})",
        "no_gender_models_alert": "В категории {gender} пока нет моделей",
        "enter_body_type": "Выберите телосложение или введите числом:",
        "enter_height_example": "Введите рост модели в числах на пример 170.",
        "enter_age_num": "Введите возраст модели числом:",
        "select_pants_style_btn": "Выберите тип кроя штанов:",
        "select_sleeve_length_btn": "Выберите тип рукавов:",
        "garment_length_notice": "Выберите длину изделия. Внимание! если ваш продукт Костюм 2-к, 3-к то длину можно не указывать.",
        "enter_length_custom": "Введите длину изделия текстом:",
        "select_photo_type": "Выберите тип фотографии:",
        "generation_confirm": "Все готово! Создать фото?",
        "confirm_params": "Подтвердите параметры и создайте фото:",
        "gen_started": "Генерация запущена, пожалуйста подождите...",
        "limit_rem_zero": "Лимит фото на сегодня исчерпан или у вас нет активной подписки.",
        "sub_none_profile": "Нет подписки",
        "buy_sub_text": "💎 Тариф {name}\n\n{desc}\n\nЦена: {price} ₽\n\nВы уверены, что хотите оформить подписку?",
        "confirm_btn": "✅ Подтвердить",
        "sub_success_alert": "✅ Подписка успешно оформлена!",
        "sub_success_4k": "✅ Вы успешно оформили подписку на 4K!\n\nПожалуйста, свяжитесь с нами (@support), чтобы мы выделили вам уникальный ключ для генерации в ультра-качестве.",
        "missing_4k_key": "Ваша подписка 4K активна, но уникальный ключ еще не назначен.\n\nПожалуйста, свяжитесь с нами (@support), чтобы мы выделили вам ключ, и вы смогли создавать фотографии.",
        "select_info_load": "Выберите нагруженность инфографики:",
        "select_model_gender": "Выберите пол модели:",
        "enter_adv1_skip": "Введите Преимущество 1 (текстом) или пропустите:",
        "enter_adv2_skip": "Введите Преимущество 2 (текстом) или пропустите:",
        "enter_adv3_skip": "Введите Преимущество 3 (текстом) или пропустите:",
        "enter_extra_info_skip": "Введите ДОП ИНФОРМАЦИЮ (до 75 символов) или пропустите:",
        "normal_gen_prompt": "Обычная генерация: Пришлите от 1 до 4-х фотографий. Когда закончите, нажмите кнопку ниже.",
        "at_least_one_photo": "Пришлите хотя бы одно фото!",
        "max_photos_alert": "Максимум 4 фото. Нажмите 'Готово', чтобы продолжить.",
        "photo_received_count": "Фото получено ({count}/4). Пришлите еще или нажмите 'Готово'.",
        "photos_received_three": "Получено 3 фото. Теперь введите текст описания (до 1000 символов):",
        "photos_received_four": "Получено 4 фото. Теперь введите текст описания (до 1000 символов):",
        "done_to_text": "Готово (перейти к тексту)",
        "enter_normal_text": "Теперь введите текст описания (до 1000 символов):",
        "has_person_ask": "Присутствие человека на фото?",
        "yes": "Да",
        "no": "Нет",
        "select_info_style_other": "Выберите стиль инфографики:",
        "loc_car": "🚗 У машины",
        "loc_cafe": "☕ У кофейни",
        "loc_wall": "🧱 У стены",
        "loc_building": "🏢 У здания",
        "loc_moscow_city": "🏙️ Москва сити",
        "loc_forest": "🌲 В лесу",
        "loc_mountains": "⛰️ В горах",
        "loc_alley": "🛣️ На аллее",
        "loc_park": "🌳 В парке",
        "loc_city": "🏙️ В городе",
        "loc_studio": "📸 Фотостудия",
        "loc_room": "🏠 В комнате",
        "loc_restaurant": "🍴 В ресторане",
        "loc_hotel": "🏨 В гостинице",
        "loc_mall": "🛍️ В торговом центре",
        "admin_stats": "📊 Статистика",
        "admin_users": "👥 Пользователи",
        "admin_search": "🔍 Поиск по ID",
        "admin_models": "💃 Модели",
        "admin_categories": "📂 Категории",
        "admin_own_prompts": "📝 Промты 'Пробовать своё'",
        "admin_own_variant_prompts": "📝 Промт 'Свой вариант'",
        "admin_howto_edit": "ℹ️ Текст помощи",
        "admin_api_keys": "🔑 API ключи Gemini",
        "admin_own_variant_api_keys": "🔑 API ключи 'Свой вариант'",
        "admin_logs": "📋 Логи сервера",
        "admin_proxy": "🌐 Состояние прокси",
        "admin_maint_on": "🛠 Включить техработы",
        "admin_maint_off": "✅ Выключить техработы",
        "admin_block": "⛔ Заблокировать",
        "admin_unblock": "✅ Разблокировать",
        "admin_list": "⤴️ К списку",
        "admin_title": "🛠 Админ-панель",
        "admin_maint_status": "Техработы: {status}",
        "admin_user_title": "👤 Пользователь {uid}",
        "admin_user_status": "Статус: {status}",
        "admin_history_no_tokens": "История транзакций больше не поддерживается (токены удалены).",
        "admin_maint_enabled": "Включены",
        "admin_maint_disabled": "Выключены",
        "admin_panel_title": "🛠 Админ-панель\nТехработы: {status}",
        "admin_reset_usage": "Использование: /reset_user <user_id>",
        "admin_reset_invalid": "Неверные параметры. Пример: /reset_user 123456789",
        "admin_reset_success": "✅ Состояние пользователя {user_id} сброшено",
        "admin_reset_error": "⚠️ Ошибка при сбросе состояния: {e}",
        "admin_stats_title": "📊 Статистика",
        "admin_stats_total_users": "Всего пользователей",
        "admin_stats_today_users": "Новых сегодня",
        "admin_stats_total_generations": "Всего генераций",
        "admin_stats_today_generations": "Генераций сегодня",
        "admin_cats_edit": "Категории (нажмите, чтобы включить/отключить):",
        "admin_saved": "Сохранено",
        "admin_prices_title": "💰 Цены категорий (нажмите для редактирования):",
        "admin_enter_id": "Введите ID пользователя (числом):",
        "admin_enter_id_error": "Укажите ID числом, например: 123456789",
        "admin_user_not_found": "Пользователь не найден",
        "admin_users_list": "👥 Пользователи:",
        "admin_models_title": "🧩 Модели",
        "admin_maint_on_success": "Техработы включены",
        "admin_maint_off_success": "Техработы выключены",
        "admin_logs_getting": "Получаю логи...",
        "admin_logs_parts": "📋 Последние логи сервера (часть {part}/{total}):",
        "admin_logs_error": "⚠️ Не удалось получить логи автоматически.",
        "admin_proxy_checking": "Проверяю прокси...",
        "admin_proxy_title": "🌐 Состояние прокси:",
        "admin_pick_cat": "Выберите категорию",
        "admin_pick_cloth": "Выберите тип одежды",
        "admin_actions": "Действия",
        "admin_model_num": "Модель #{mid}",
        "admin_send_photo": "Пришлите фото модели (изображение сообщением)",
        "admin_need_photo": "Нужно отправить фото",
        "admin_send_prompt": "Пришлите промт для этой модели (текстом)",
        "admin_prompt_empty": "Промт не может быть пустым. Отправьте текст промта или .txt файл.",
        "admin_send_name": "Укажите название модели (например: Model 1)",
        "admin_model_created": "Создана модель #{mid}",
        "admin_enter_prompt_title": "Введите название промта (сообщением).",
        "admin_enter_prompt_text": "Отправьте текст промта.",
        "admin_prompt_created": "Промт создан #{pid}",
        "admin_enter_new_name": "Введите новое имя модели сообщением",
        "admin_send_new_photo": "Пришлите новое фото модели (изображением в сообщении)",
        "admin_photo_updated": "Фото обновлено для модели #{mid}",
        "admin_name_updated": "Имя обновлено",
        "admin_pick_prompt": "Выберите промт",
        "admin_deleted_return": "Удалено. Вернитесь к списку.",
        "admin_deleted": "Удалено",
        "admin_broadcast_done": "Рассылка завершена",
        "admin_broadcast_text_req": "Пришлите текст для рассылки (сообщением). Потом можно будет добавить картинку или пропустить.",
        "admin_broadcast_text_ok": "Текст принят. Прикрепите изображение (фото), видео или нажмите 'Пропустить'.",
        "admin_broadcast_preview": "Предпросмотр рассылки:\n\n{text}",
        "admin_broadcast_cancel": "Отменено.",
        "admin_broadcast_success": "✅ Рассылка отправлена",
        "admin_broadcast_error": "❌ Ошибка отправки: {e}",
        "admin_user_invalid": "Неверный пользователь",
        "admin_status_updated": "Статус обновлён",
        "admin_gemini_keys": "🔑 Ключи Gemini:",
        "admin_gemini_add_key": "Отправьте новый GEMINI_API_KEY (строкой). Затем укажите приоритет (целое) или /skip",
        "admin_gemini_add_key_own": "Отправьте новый GEMINI_API_KEY для 'Свой вариант' (строкой). Затем укажите приоритет (целое) или /skip",
        "admin_gemini_priority": "Укажите приоритет (целое, больше — выше приоритет) или отправьте /skip",
        "admin_gemini_key_added": "Ключ добавлен",
        "admin_gemini_key_updated": "Ключ обновлен",
        "admin_gemini_send_token": "Пришлите новый токен (или /skip чтобы оставить старый)",
        "admin_gemini_priority_req": "Укажите новый приоритет (целое) или /skip",
        "admin_own_variant_keys": "🔑 Ключи 'Свой вариант':",
        "admin_own_variant_prompt": "Промт «Свой вариант»:",
        "admin_own_variant_prompt_full": "📋 Текущий промт «Свой вариант»:\n\n{text}",
        "admin_own_variant_prompt_none": "Промт «Свой вариант» не задан.",
        "admin_own_variant_prompt_edit_req": "Отправьте новый промт (текстом):",
        "admin_own_prompt_names": "Шаг {idx}",
        "admin_logs_server": "📋 Последние логи сервера:",
        "admin_list_all": "📋 Список всех",
        "admin_add": "➕ Добавить",
        "admin_list": "📋 Список",
        "admin_rename": "📝 Переименовать",
        "admin_change_photo": "🖼 Изменить фото",
        "admin_change_prompt": "📝 Изменить промт",
        "admin_delete": "❌ Удалить",
        "admin_to_list": "К списку",
        "admin_add_key": "➕ Добавить ключ",
        "admin_cancel": "❌ Отмена",
        "admin_send": "🚀 Отправить",
        "admin_step_model": "Шаг 1 (Модель)",
        "admin_step_gen": "Шаг 3 (Генерация)",
        "admin_view": "👁 Посмотреть",
        "admin_edit": "📝 Изменить",
        "admin_edit_btn": "📝 Редактировать",
        "admin_models_list": "Список моделей",
        "agreement_not_set": "Пользовательское соглашение не задано.",
        "admin_prices_edit_notice": "Текущий статус категории «{name}»: {status}\n\nВы можете изменить статус категории в админ-панели на g-box.space.",
        "admin_own_prompt_step1": "Шаг 1 — Описание модели",
        "admin_own_prompt_step2": "Шаг 2 — (не используется)",
        "admin_own_prompt_step3": "Шаг 3 — Финальная генерация",
        "admin_own_prompt_edit_req": "{name}: отправьте текст промта (или .txt)",
        "admin_price_empty": "Цена пуста. Отправьте число или число с точкой.",
        "admin_price_invalid": "Цена должна быть больше нуля.",
        "admin_price_format_error": "Неверный формат цены. Отправьте число или число с точкой (например: 1, 1.2, 2.0).",
        "admin_txt_req": "Пришлите .txt файл (text/plain) или текстом.",
        "admin_rebind_start": "Запускаю перепривязку фото моделей... Это может занять время.",
        "admin_rebind_no_token": "OLD_BOT_TOKEN не задан в .env",
        "admin_rebind_done": "Готово. Обновлено: {updated}, ошибок: {failed}.",
        "admin_gemini_key_val_error": "Неверный приоритет. Введите целое число или /skip",
        "admin_gemini_token_empty": "Токен пуст. Пришлите строку или /skip",
        "admin_own_variant_key_show": "Ключ #{key_id}: {token}\nСтатус: {state_txt}",
        "admin_whitebg_notice": "Для этой категории добавьте только промт.",
    },
    "en": {
        "start_welcome": "Welcome to AI-ROOM! Choose a section:",
        "accept_terms": "Accept.",
        "subscribed": "I subscribed",
        "subscribe_channel": "Please subscribe to our channel to use the bot:",
        "menu_market": "For Marketplaces",
        "menu_profile": "Profile",
        "menu_howto": "Instructions",
        "menu_settings": "Settings",
        "back_main": "⬅️ Back to menu",
        "back": "⬅️ Back",
        "lang_ru": "Russian",
        "lang_en": "English",
        "lang_vi": "Tiếng Việt",
        "select_lang": "Choose language:",
        "profile_info": "👤 Profile\nID: {id}\nSubscription: {sub}\nGenerations left today: {daily_rem}\n\nChoose an action:",
        "sub_none": "No subscription",
        "sub_active": "{plan} (until {date})",
        "menu_subscription": "Subscription",
        "menu_history": "Generation History",
        "menu_referral": "Earn with us",
        "buy_plan": "Get Subscription",
        "trial_info": "Free trial available: 1 day and 5 generations!",
        "get_trial": "Get Free Trial",
        "marketplace_menu": "📦 Marketplace section:",
        "create_own_variant": "✨ Own variant",
        "upload_photo": "Upload photos. Send them one by one or as a group.",
        "enter_prompt": "Enter description (up to 1000 characters):",
        "select_format": "Select format:",
        "history_title": "Last 20 generations:",
        "history_item": "PID: {pid}\nDate: {date}",
        "agreement": "User Agreement",
        "how_to": "How to use the bot",
        "maintenance": "Maintenance in progress. Please wait.",
        "error_api": "An error occurred during generation. Please try again later.",
        "rate_limit": "Too many requests. Please wait 20 seconds.",
        "create_normal_gen": "✨ NORMAL GENERATION (up to 3 photos)",
        "create_photo": "Create photo",
        "skip": "Skip",
        "select_body_type": "Choose body type or enter a number:",
        "enter_height": "Enter model height in numbers (e.g., 170).",
        "enter_age": "Enter model age in numbers:",
        "select_pants_style": "Select pants style:",
        "select_sleeve_length": "Select sleeve length:",
        "select_garment_length": "Select garment length. Note: for suit products, length is optional.",
        "select_view": "Select photo angle:",
        "select_camera_dist": "Select camera distance (Far - Medium - Close):",
        "select_quality": "Select quality:",
        "gen_in_progress": "Generation started. Please wait...",
        "gen_success": "Your photo is ready!",
        "gen_error": "Generation error. Please try again.",
        "quality_hd": "Standard (HD)",
        "quality_2k": "Premium (2K)",
        "quality_4k": "Ultra (4K)",
        "view_front": "Front",
        "view_back": "Back",
        "view_side": "Side",
        "cat_female": "👱‍♀️ Female",
        "cat_male": "👨 Male",
        "cat_child": "🧒 Children's clothing",
        "cat_storefront": "🏬 Storefront photo",
        "cat_whitebg": "⚪ On white background",
        "cat_random": "👕 Clothing & Shoes (Random)",
        "cat_own": "💃 Own MODEL variant",
        "cat_own_variant": "🖼️ Own BACKGROUND variant",
        "cat_infographic_clothing": "🖼️ Infographic: Clothing",
        "cat_infographic_other": "📦 Infographic: Other",
        "pose_normal": "Normal",
        "pose_unusual": "Unusual",
        "pose_vulgar": "Vulgar",
        "dist_close": "Close",
        "dist_medium": "Medium",
        "dist_far": "Far",
        "load_min": "Minimum",
        "load_med": "Medium",
        "load_max": "Maximum",
        "loc_outdoor": "Outdoor",
        "loc_indoor": "Indoor",
        "season_winter": "Winter",
        "season_summer": "Summer",
        "season_autumn": "Autumn",
        "season_spring": "Spring",
        "holiday_wedding": "💍 Wedding",
        "holiday_newyear": "🎄 New Year",
        "holiday_bday": "🎂 Birthday",
        "holiday_march8": "💐 March 8",
        "holiday_feb23": "🎖️ Feb 23",
        "holiday_may9": "May 9",
        "holiday_momday": "👩‍👧 Mother's Day",
        "holiday_teacherday": "👩‍🏫 Teacher's Day",
        "holiday_russiaday": "🇷🇺 Russia Day",
        "custom_variant": "✏️ Custom variant",
        "gender_male": "👨 Male",
        "gender_female": "👱‍♀️ Female",
        "gender_boy": "👦 Boy",
        "gender_girl": "👧 Girl",
        "gender_neutral": "👫 Neutral",
        "gender_unisex": "👫 UNISEX",
        "style_modern": "Modern",
        "style_simple": "Simple",
        "style_bright": "Bright",
        "style_premium": "Premium",
        "style_child": "Children's",
        "style_tech": "Technological",
        "style_natural": "Natural",
        "style_retro": "Retro",
        "style_classic": "Classic",
        "style_atmos": "Atmospheric",
        "font_modern": "Modern",
        "font_serif": "Serif",
        "font_sans": "Sans-serif",
        "font_bold": "Bold",
        "font_italic": "Italic",
        "font_semibold": "Semibold",
        "font_hand": "Handwritten",
        "font_decor": "Decorative",
        "font_mono": "Monospace",
        "font_narrow": "Narrow",
        "font_tech": "Tech",
        "lang_ru_btn": "Russian",
        "lang_en_btn": "English",
        "lang_vi_btn": "Vietnamese",
        "pants_relaxed": "Relaxed fit",
        "pants_slim": "Slim fit",
        "pants_banana": "Banana",
        "pants_flare_knee": "Flare knee",
        "pants_baggy": "Baggy",
        "pants_mom": "Mom",
        "pants_straight": "Straight",
        "sleeve_normal": "Normal",
        "sleeve_long": "Long",
        "sleeve_three_quarter": "Three quarter",
        "sleeve_elbow": "Elbow",
        "sleeve_short": "Short",
        "sleeve_none": "Sleeveless",
        "len_short_top": "Short top",
        "len_regular_top": "Regular top",
        "len_to_waist": "To waist",
        "len_below_waist": "Below waist",
        "len_mid_thigh": "Mid-thigh",
        "len_to_knees": "To knees",
        "len_below_knees": "Below knees",
        "len_midi": "Midi",
        "len_to_ankles": "To ankles",
        "len_to_floor": "To floor",
        "enter_product_name": "Enter product name (up to 75 characters):",
        "enter_width": "Enter width (or skip):",
        "enter_height_dim": "Enter height (or skip):",
        "enter_length_dim": "Enter length (or skip):",
        "enter_adv1": "Enter first advantage (up to 180 characters):",
        "enter_adv2": "Enter second advantage (up to 180 characters):",
        "enter_adv3": "Enter third advantage (up to 180 characters):",
        "enter_additional": "Enter additional info (up to 100 characters):",
        "select_info_style": "Select infographic style:",
        "select_font_type": "Select font type:",
        "select_info_lang": "Select infographic language:",
        "select_holiday": "Select holiday (or skip):",
        "select_season": "Select season (or skip):",
        "select_gender": "Select product gender:",
        "select_loc_group": "Select location type:",
        "select_location": "Select location:",
        "enter_custom_loc": "Enter custom location (up to 100 characters):",
        "enter_custom_holiday": "Enter custom holiday (up to 30 characters):",
        "enter_custom_style": "Enter custom style (up to 20 characters):",
        "enter_custom_font": "Enter custom font (up to 20 characters):",
        "enter_custom_lang": "Enter custom language:",
        "upload_background": "Upload the 1st photo that you like:",
        "upload_product": "Upload product photo:",
        "select_pose": "Select pose:",
        "enter_model_size": "Enter model size in numbers (or skip):",
        "child_category_notice": "Note: prompts for children's category are created separately.",
        "disclaimer": "Attention! Results may vary based on specified parameters.",
        "model_label": "Model",
        "presets_label": "Clothing Presets",
        "cloth_coat": "Coat",
        "cloth_dress": "Dress",
        "cloth_shorts": "Shorts",
        "cloth_suit": "Suit",
        "cloth_loungewear": "Loungewear",
        "cloth_overall": "Overall",
        "cloth_skirt": "Skirt",
        "cloth_shoes": "Shoes",
        "subcat_outerwear": "Outerwear",
        "subcat_top": "Tops",
        "subcat_bottom": "Bottoms",
        "subcat_underwear": "Underwear",
        "subcat_sport": "Sportswear",
        "subcat_sleepwear": "Sleepwear",
        "subcat_swimwear": "Swimwear",
        "subcat_accessories": "Accessories",
        "subcat_socks": "Socks",
        "subcat_dresses": "Dresses & Overalls",
        "other": "Other",
        "maintenance_alert": "🛠 Maintenance in progress. Subscription will be extended.",
        "disclaimer_text": "Note: appearance and other parameters may vary based on specified options.",
        "no_models_in_category_alert": "No models in this category yet",
        "model_presets_title": "Clothing presets\n\nModel: {name} ({index}/{total})",
        "gender_presets_title": "Presets for {gender}\n\nModel: {name} ({index}/{total})",
        "no_gender_models_alert": "No models in category {gender} yet",
        "enter_body_type": "Choose body type or enter a number:",
        "enter_height_example": "Enter model height in numbers (e.g., 170).",
        "enter_age_num": "Enter model age in numbers:",
        "select_pants_style_btn": "Select pants style:",
        "select_sleeve_length_btn": "Select sleeve length:",
        "garment_length_notice": "Select garment length. Note: for suit products, length is optional.",
        "enter_length_custom": "Enter garment length as text:",
        "select_photo_type": "Select photo type:",
        "generation_confirm": "Everything is ready! Create photo?",
        "confirm_params": "Confirm parameters and create photo:",
        "gen_started": "Generation started, please wait...",
        "limit_rem_zero": "Daily limit reached or no active subscription.",
        "sub_none_profile": "No subscription",
        "buy_sub_text": "💎 Plan {name}\n\n{desc}\n\nPrice: {price} ₽\n\nAre you sure you want to subscribe?",
        "confirm_btn": "✅ Confirm",
        "sub_success_alert": "✅ Subscription successfully activated!",
        "select_info_load": "Select infographic load:",
        "enter_adv1_skip": "Enter Advantage 1 (text) or skip:",
        "enter_adv2_skip": "Enter Advantage 2 (text) or skip:",
        "enter_adv3_skip": "Enter Advantage 3 (text) or skip:",
        "enter_extra_info_skip": "Enter EXTRA INFO (up to 75 chars) or skip:",
        "normal_gen_prompt": "Normal generation: Send 1 to 4 photos. When finished, press the button below.",
        "at_least_one_photo": "Send at least one photo!",
        "max_photos_alert": "Maximum 4 photos. Press 'Done' to continue.",
        "photo_received_count": "Photo received ({count}/4). Send more or press 'Done'.",
        "photos_received_three": "3 photos received. Now enter description (up to 1000 chars):",
        "photos_received_four": "4 photos received. Now enter description (up to 1000 chars):",
        "done_to_text": "Done (proceed to text)",
        "enter_normal_text": "Now enter description (up to 1000 chars):",
        "loc_car": "🚗 By the car",
        "loc_cafe": "☕ At the cafe",
        "loc_wall": "🧱 By the wall",
        "loc_building": "🏢 By the building",
        "loc_moscow_city": "🏙️ Moscow City",
        "loc_forest": "🌲 In the forest",
        "loc_mountains": "⛰️ In the mountains",
        "loc_alley": "🛣️ On the alley",
        "loc_park": "🌳 In the park",
        "loc_city": "🏙️ In the city",
        "loc_studio": "📸 Photo studio",
        "loc_room": "🏠 In the room",
        "loc_restaurant": "🍴 In the restaurant",
        "loc_hotel": "🏨 In the hotel",
        "loc_mall": "🛍️ In the mall",
        "admin_stats": "📊 Statistics",
        "admin_users": "👥 Users",
        "admin_search": "🔍 ID Search",
        "admin_models": "💃 Models",
        "admin_categories": "📂 Categories",
        "admin_own_prompts": "📝 'Try own' Prompts",
        "admin_own_variant_prompts": "📝 'Own variant' Prompt",
        "admin_howto_edit": "ℹ️ Help Text",
        "admin_api_keys": "🔑 Gemini API Keys",
        "admin_own_variant_api_keys": "🔑 'Own variant' API Keys",
        "admin_logs": "📋 Server Logs",
        "admin_proxy": "🌐 Proxy Status",
        "admin_maint_on": "🛠 Enable Maintenance",
        "admin_maint_off": "✅ Disable Maintenance",
        "admin_block": "⛔ Block",
        "admin_unblock": "✅ Unblock",
        "admin_list": "⤴️ To List",
        "admin_title": "🛠 Admin Panel",
        "admin_maint_status": "Maintenance: {status}",
        "admin_user_title": "👤 User {uid}",
        "admin_user_status": "Status: {status}",
        "admin_history_no_tokens": "Transaction history is no longer supported (tokens removed).",
        "admin_maint_enabled": "Enabled",
        "admin_maint_disabled": "Disabled",
        "admin_panel_title": "🛠 Admin Panel\nMaintenance: {status}",
        "admin_reset_usage": "Usage: /reset_user <user_id>",
        "admin_reset_invalid": "Invalid parameters. Example: /reset_user 123456789",
        "admin_reset_success": "✅ User {user_id} state reset",
        "admin_reset_error": "⚠️ Error resetting state: {e}",
        "admin_stats_title": "📊 Statistics",
        "admin_stats_total_users": "Total users",
        "admin_stats_today_users": "New today",
        "admin_stats_total_generations": "Total generations",
        "admin_stats_today_generations": "Generations today",
        "admin_cats_edit": "Categories (click to toggle):",
        "admin_saved": "Saved",
        "admin_prices_title": "💰 Category prices (click to edit):",
        "admin_enter_id": "Enter user ID (number):",
        "admin_enter_id_error": "Enter ID as a number, e.g., 123456789",
        "admin_user_not_found": "User not found",
        "admin_users_list": "👥 Users:",
        "admin_models_title": "🧩 Models",
        "admin_maint_on_success": "Maintenance enabled",
        "admin_maint_off_success": "Maintenance disabled",
        "admin_logs_getting": "Getting logs...",
        "admin_logs_parts": "📋 Last server logs (part {part}/{total}):",
        "admin_logs_error": "⚠️ Failed to get logs automatically.",
        "admin_proxy_checking": "Checking proxy...",
        "admin_proxy_title": "🌐 Proxy status:",
        "admin_pick_cat": "Pick a category",
        "admin_pick_cloth": "Pick clothing type",
        "admin_actions": "Actions",
        "admin_model_num": "Model #{mid}",
        "admin_send_photo": "Send model photo (as an image message)",
        "admin_need_photo": "Need to send a photo",
        "admin_send_prompt": "Send prompt for this model (as text)",
        "admin_prompt_empty": "Prompt cannot be empty. Send prompt text or .txt file.",
        "admin_send_name": "Enter model name (e.g., Model 1)",
        "admin_model_created": "Model #{mid} created",
        "admin_enter_prompt_title": "Enter prompt title (as a message).",
        "admin_enter_prompt_text": "Send prompt text.",
        "admin_prompt_created": "Prompt #{pid} created",
        "admin_enter_new_name": "Enter new model name as a message",
        "admin_send_new_photo": "Send new model photo (as an image in a message)",
        "admin_photo_updated": "Photo updated for model #{mid}",
        "admin_name_updated": "Name updated",
        "admin_pick_prompt": "Pick a prompt",
        "admin_deleted_return": "Deleted. Return to list.",
        "admin_deleted": "Deleted",
        "admin_broadcast_done": "Broadcast finished",
        "admin_broadcast_text_req": "Send text for broadcast (as a message). Then you can add a picture or skip.",
        "admin_broadcast_text_ok": "Text accepted. Attach image (photo), video, or press 'Skip'.",
        "admin_broadcast_preview": "Broadcast preview:\n\n{text}",
        "admin_broadcast_cancel": "Cancelled.",
        "admin_broadcast_success": "✅ Broadcast sent",
        "admin_broadcast_error": "❌ Send error: {e}",
        "admin_user_invalid": "Invalid user",
        "admin_status_updated": "Status updated",
        "admin_gemini_keys": "🔑 Gemini Keys:",
        "admin_gemini_add_key": "Send new GEMINI_API_KEY (string). Then specify priority (integer) or /skip",
        "admin_gemini_add_key_own": "Send new GEMINI_API_KEY for 'Own variant' (string). Then specify priority (integer) or /skip",
        "admin_gemini_priority": "Specify priority (integer, higher is higher priority) or send /skip",
        "admin_gemini_key_added": "Key added",
        "admin_gemini_key_updated": "Key updated",
        "admin_gemini_send_token": "Send new token (or /skip to keep old one)",
        "admin_gemini_priority_req": "Specify new priority (integer) or /skip",
        "admin_own_variant_keys": "🔑 'Own variant' Keys:",
        "admin_own_variant_prompt": "Prompt 'Own variant':",
        "admin_own_variant_prompt_full": "📋 Current 'Own variant' prompt:\n\n{text}",
        "admin_own_variant_prompt_none": "Prompt 'Own variant' not set.",
        "admin_own_variant_prompt_edit_req": "Send new prompt (as text):",
        "admin_own_prompt_names": "Step {idx}",
        "admin_logs_server": "📋 Last server logs:",
        "admin_list_all": "📋 List all",
        "admin_add": "➕ Add",
        "admin_list": "📋 List",
        "admin_rename": "📝 Rename",
        "admin_change_photo": "🖼 Change photo",
        "admin_change_prompt": "📝 Change prompt",
        "admin_delete": "❌ Delete",
        "admin_to_list": "To list",
        "admin_add_key": "➕ Add key",
        "admin_cancel": "❌ Cancel",
        "admin_send": "🚀 Send",
        "admin_step_model": "Step 1 (Model)",
        "admin_step_gen": "Step 3 (Generation)",
        "admin_view": "👁 View",
        "admin_edit": "📝 Edit",
        "admin_edit_btn": "📝 Edit",
        "admin_models_list": "Models list",
        "agreement_not_set": "User agreement not set.",
        "admin_prices_edit_notice": "Current status of category '{name}': {status}\n\nYou can change the category status in the admin panel at g-box.space.",
        "admin_own_prompt_step1": "Step 1 — Model description",
        "admin_own_prompt_step2": "Step 2 — (not used)",
        "admin_own_prompt_step3": "Step 3 — Final generation",
        "admin_own_prompt_edit_req": "{name}: send prompt text (or .txt)",
        "admin_price_empty": "Price is empty. Send a number or a decimal.",
        "admin_price_invalid": "Price must be greater than zero.",
        "admin_price_format_error": "Invalid price format. Send a number or a decimal (e.g., 1, 1.2, 2.0).",
        "admin_txt_req": "Please send a .txt file (text/plain) or text.",
        "admin_rebind_start": "Starting model photo rebinding... This may take some time.",
        "admin_rebind_no_token": "OLD_BOT_TOKEN not set in .env",
        "admin_rebind_done": "Done. Updated: {updated}, errors: {failed}.",
        "admin_gemini_key_val_error": "Invalid priority. Enter an integer or /skip",
        "admin_gemini_token_empty": "Token is empty. Send a token string or /skip",
        "admin_own_variant_key_show": "Key #{key_id}: {token}\nStatus: {state_txt}",
        "admin_whitebg_notice": "For this category, add only a prompt.",
    },
    "vi": {
        "start_welcome": "Chào mừng đến với AI-ROOM! Chọn một mục:",
        "accept_terms": "Chấp nhận.",
        "subscribed": "Tôi đã đăng ký",
        "subscribe_channel": "Vui lòng đăng ký kênh của chúng tôi để sử dụng bot:",
        "menu_market": "Cho Sàn TMĐT",
        "menu_profile": "Hồ sơ",
        "menu_howto": "Hướng dẫn",
        "menu_settings": "Cài đặt",
        "back_main": "⬅️ Quay lại menu",
        "back": "⬅️ Quay lại",
        "lang_ru": "Tiếng Nga",
        "lang_en": "Tiếng Anh",
        "lang_vi": "Tiếng Việt",
        "select_lang": "Chọn ngôn ngữ:",
        "profile_info": "👤 Hồ sơ\nID: {id}\nGói đăng ký: {sub}\nSố lượt tạo còn lại hôm nay: {daily_rem}\n\nChọn một hành động:",
        "sub_none": "Chưa có gói đăng ký",
        "sub_active": "{plan} (đến {date})",
        "menu_subscription": "Gói đăng ký",
        "menu_history": "Lịch sử tạo",
        "menu_referral": "Kiếm tiền cùng chúng tôi",
        "buy_plan": "Đăng ký gói",
        "trial_info": "Dùng thử miễn phí: 1 ngày và 5 lượt tạo!",
        "get_trial": "Nhận dùng thử",
        "marketplace_menu": "📦 Mục dành cho Sàn TMĐT:",
        "create_own_variant": "✨ Biến thể riêng",
        "upload_photo": "Tải ảnh lên. Gửi từng ảnh hoặc gửi theo nhóm.",
        "enter_prompt": "Nhập mô tả (tối đa 1000 ký tự):",
        "select_format": "Chọn định dạng:",
        "history_title": "20 lượt tạo gần nhất:",
        "history_item": "PID: {pid}\nNgày: {date}",
        "agreement": "Thỏa thuận người dùng",
        "how_to": "Cách sử dụng bot",
        "maintenance": "Đang bảo trì. Vui lòng đợi.",
        "error_api": "Đã xảy ra lỗi khi tạo. Vui lòng thử lại sau.",
        "rate_limit": "Quá nhiều yêu cầu. Vui lòng đợi 20 giây.",
        "create_normal_gen": "✨ TẠO THÔNG THƯỜNG (tối đa 3 ảnh)",
        "create_photo": "Tạo ảnh",
        "skip": "Bỏ qua",
        "select_body_type": "Chọn vóc dáng hoặc nhập số:",
        "enter_height": "Nhập chiều cao người mẫu bằng số (ví dụ: 170).",
        "enter_age": "Nhập tuổi người mẫu bằng số:",
        "select_pants_style": "Chọn kiểu dáng quần:",
        "select_sleeve_length": "Chọn chiều dài tay áo:",
        "select_garment_length": "Chọn chiều dài sản phẩm. Lưu ý: với bộ vest, chiều dài là tùy chọn.",
        "select_view": "Chọn góc chụp:",
        "select_camera_dist": "Chọn khoảng cách máy ảnh (Xa - Trung bình - Gần):",
        "select_quality": "Chọn chất lượng:",
        "gen_in_progress": "Đang tiến hành tạo. Vui lòng đợi...",
        "gen_success": "Ảnh của bạn đã sẵn sàng!",
        "gen_error": "Lỗi khi tạo. Vui lòng thử lại.",
        "quality_hd": "Tiêu chuẩn (HD)",
        "quality_2k": "Cao cấp (2K)",
        "quality_4k": "Siêu nét (4K)",
        "view_front": "Mặt trước",
        "view_back": "Mặt sau",
        "view_side": "Mặt bên",
        "cat_female": "👱‍♀️ Nữ",
        "cat_male": "👨 Nam",
        "cat_child": "🧒 Quần áo trẻ em",
        "cat_storefront": "🏬 Ảnh cửa hàng",
        "cat_whitebg": "⚪ Trên nền trắng",
        "cat_random": "👕 Quần áo & Giày (Ngẫu nhiên)",
        "cat_own": "💃 Biến thể NGƯỜI MẪU riêng",
        "cat_own_variant": "🖼️ Biến thể NỀN riêng",
        "cat_infographic_clothing": "🖼️ Đồ họa: Quần áo",
        "cat_infographic_other": "📦 Đồ họa: Khác",
        "pose_normal": "Bình thường",
        "pose_unusual": "Bất thường",
        "pose_vulgar": "Hở hang",
        "dist_close": "Gần",
        "dist_medium": "Trung bình",
        "dist_far": "Xa",
        "load_min": "Tối thiểu",
        "load_med": "Trung bình",
        "load_max": "Tối đa",
        "loc_outdoor": "Ngoài trời",
        "loc_indoor": "Trong nhà",
        "season_winter": "Mùa đông",
        "season_summer": "Mùa hè",
        "season_autumn": "Mùa thu",
        "season_spring": "Mùa xuân",
        "holiday_wedding": "💍 Đám cưới",
        "holiday_newyear": "🎄 Năm mới",
        "holiday_bday": "🎂 Sinh nhật",
        "holiday_march8": "💐 8 tháng 3",
        "holiday_feb23": "🎖️ 23 tháng 2",
        "holiday_may9": "9 tháng 5",
        "holiday_momday": "👩‍👧 Ngày của Mẹ",
        "holiday_teacherday": "👩‍🏫 Ngày Nhà giáo",
        "holiday_russiaday": "🇷🇺 Ngày nước Nga",
        "custom_variant": "✏️ Biến thể tùy chỉnh",
        "gender_male": "👨 Nam",
        "gender_female": "👱‍♀️ Nữ",
        "gender_boy": "👦 Bé trai",
        "gender_girl": "👧 Bé gái",
        "gender_neutral": "👫 Trung tính",
        "gender_unisex": "👫 UNISEX",
        "style_modern": "Hiện đại",
        "style_simple": "Đơn giản",
        "style_bright": "Sáng sủa",
        "style_premium": "Cao cấp",
        "style_child": "Trẻ em",
        "style_tech": "Công nghệ",
        "style_natural": "Tự nhiên",
        "style_retro": "Hoài cổ",
        "style_classic": "Cổ điển",
        "style_atmos": "Không khí",
        "font_modern": "Hiện đại",
        "font_serif": "Có chân",
        "font_sans": "Không chân",
        "font_bold": "Đậm",
        "font_italic": "Nghiêng",
        "font_semibold": "Bán đậm",
        "font_hand": "Viết tay",
        "font_decor": "Trang trí",
        "font_mono": "Đơn cách",
        "font_narrow": "Hẹp",
        "font_tech": "Công nghệ",
        "lang_ru_btn": "Tiếng Nga",
        "lang_en_btn": "Tiếng Anh",
        "lang_vi_btn": "Tiếng Việt",
        "pants_relaxed": "Dáng rộng",
        "pants_slim": "Dáng ôm",
        "pants_banana": "Dáng chuối",
        "pants_flare_knee": "Ống loe",
        "pants_baggy": "Dáng thụng",
        "pants_mom": "Dáng mom",
        "pants_straight": "Dáng đứng",
        "sleeve_normal": "Bình thường",
        "sleeve_long": "Dài tay",
        "sleeve_three_quarter": "Tay lỡ",
        "sleeve_elbow": "Đến khuỷu tay",
        "sleeve_short": "Ngắn tay",
        "sleeve_none": "Sát nách",
        "len_short_top": "Áo ngắn",
        "len_regular_top": "Áo thường",
        "len_to_waist": "Đến eo",
        "len_below_waist": "Dưới eo",
        "len_mid_thigh": "Đến giữa đùi",
        "len_to_knees": "Đến gối",
        "len_below_knees": "Dưới gối",
        "len_midi": "Midi",
        "len_to_ankles": "Đến cổ chân",
        "len_to_floor": "Đến sàn",
        "enter_product_name": "Nhập tên sản phẩm (tối đa 75 ký tự):",
        "enter_width": "Nhập chiều rộng (hoặc bỏ qua):",
        "enter_height_dim": "Nhập chiều cao (hoặc bỏ qua):",
        "enter_length_dim": "Nhập chiều dài (hoặc bỏ qua):",
        "enter_adv1": "Nhập ưu điểm thứ nhất (tối đa 180 ký tự):",
        "enter_adv2": "Nhập ưu điểm thứ hai (tối đa 180 ký tự):",
        "enter_adv3": "Nhập ưu điểm thứ ba (tối đa 180 ký tự):",
        "enter_additional": "Nhập thông tin bổ sung (tối đa 100 ký tự):",
        "select_info_style": "Chọn phong cách đồ họa:",
        "select_font_type": "Chọn kiểu phông chữ:",
        "select_info_lang": "Chọn ngôn ngữ đồ họa:",
        "select_holiday": "Chọn ngày lễ (hoặc bỏ qua):",
        "select_season": "Chọn mùa (hoặc bỏ qua):",
        "select_gender": "Chọn giới tính sản phẩm:",
        "select_loc_group": "Chọn loại địa điểm:",
        "select_location": "Chọn địa điểm:",
        "enter_custom_loc": "Nhập địa điểm tùy chỉnh (tối đa 100 ký tự):",
        "enter_custom_holiday": "Nhập ngày lễ tùy chỉnh (tối đa 30 ký tự):",
        "enter_custom_style": "Nhập phong cách tùy chỉnh (tối đa 20 ký tự):",
        "enter_custom_font": "Nhập phông chữ tùy chỉnh (tối đa 20 ký tự):",
        "enter_custom_lang": "Nhập ngôn ngữ tùy chỉnh:",
        "upload_background": "Tải lên bức ảnh thứ nhất mà bạn thích:",
        "upload_product": "Tải ảnh sản phẩm lên:",
        "select_pose": "Chọn tư thế:",
        "enter_model_size": "Nhập kích thước người mẫu (hoặc bỏ qua):",
        "child_category_notice": "Lưu ý: các yêu cầu cho mục trẻ em được tạo riêng.",
        "disclaimer": "Chú ý! Kết quả có thể thay đổi dựa trên các thông số đã đặt.",
        "model_label": "Người mẫu",
        "presets_label": "Cài đặt quần áo",
        "cloth_coat": "Áo khoác",
        "cloth_dress": "Váy liền",
        "cloth_shorts": "Quần đùi",
        "cloth_suit": "Bộ vest",
        "cloth_loungewear": "Đồ mặc nhà",
        "cloth_overall": "Đồ liền thân",
        "cloth_skirt": "Chân váy",
        "cloth_shoes": "Giày dép",
        "subcat_outerwear": "Áo khoác ngoài",
        "subcat_top": "Áo các loại",
        "subcat_bottom": "Quần các loại",
        "subcat_underwear": "Đồ lót",
        "subcat_sport": "Đồ thể thao",
        "subcat_sleepwear": "Đồ ngủ",
        "subcat_swimwear": "Đồ bơi",
        "subcat_accessories": "Phụ kiện",
        "subcat_socks": "Tất",
        "subcat_dresses": "Váy & Đồ liền",
        "other": "Khác",
        "maintenance_alert": "Đang bảo trì. Gói đăng ký sẽ được gia hạn.",
        "disclaimer_text": "Lưu ý: ngoại hình và các thông số khác có thể thay đổi tùy thuộc vào các tùy chọn đã chọn.",
        "no_models_in_category_alert": "Chưa có người mẫu trong mục này",
        "model_presets_title": "Cài đặt quần áo\n\nNgười mẫu: {name} ({index}/{total})",
        "gender_presets_title": "Cài đặt cho {gender}\n\nNgười mẫu: {name} ({index}/{total})",
        "no_gender_models_alert": "Chưa có người mẫu trong mục {gender}",
        "enter_body_type": "Chọn vóc dáng hoặc nhập số:",
        "enter_height_example": "Nhập chiều cao người mẫu bằng số (ví dụ: 170).",
        "enter_age_num": "Nhập tuổi người mẫu bằng số:",
        "select_pants_style_btn": "Chọn kiểu dáng quần:",
        "select_sleeve_length_btn": "Chọn chiều dài tay áo:",
        "garment_length_notice": "Chọn chiều dài sản phẩm. Lưu ý: với bộ vest, chiều dài là tùy chọn.",
        "enter_length_custom": "Nhập chiều dài sản phẩm bằng văn bản:",
        "select_photo_type": "Chọn loại ảnh:",
        "generation_confirm": "Tất cả đã sẵn sàng! Tạo ảnh?",
        "confirm_params": "Xác nhận thông số và tạo ảnh:",
        "gen_started": "Đang tiến hành tạo, vui lòng đợi...",
        "limit_rem_zero": "Đã hết lượt tạo hôm nay hoặc chưa có gói đăng ký.",
        "sub_none_profile": "Chưa có gói đăng ký",
        "buy_sub_text": "💎 Gói {name}\n\n{desc}\n\nGiá: {price} ₽\n\nBạn có chắc chắn muốn đăng ký?",
        "confirm_btn": "✅ Xác nhận",
        "sub_success_alert": "✅ Đã đăng ký gói thành công!",
        "select_info_load": "Chọn mức độ đồ họa:",
        "enter_adv1_skip": "Nhập ưu điểm 1 (văn bản) hoặc bỏ qua:",
        "enter_adv2_skip": "Nhập ưu điểm 2 (văn bản) hoặc bỏ qua:",
        "enter_adv3_skip": "Nhập ưu điểm 3 (văn bản) hoặc bỏ qua:",
        "enter_extra_info_skip": "Nhập THÔNG TIN THÊM (tối đa 75 ký tự) hoặc bỏ qua:",
        "normal_gen_prompt": "Tạo thông thường: Gửi 1 đến 4 ảnh. Sau khi hoàn tất, nhấn nút bên dưới.",
        "at_least_one_photo": "Gửi ít nhất một ảnh!",
        "max_photos_alert": "Tối đa 4 ảnh. Nhấn 'Xong' để tiếp tục.",
        "photo_received_count": "Đã nhận ảnh ({count}/4). Gửi thêm hoặc nhấn 'Xong'.",
        "photos_received_three": "Đã nhận 3 ảnh. Bây giờ hãy nhập mô tả (tối đa 1000 ký tự):",
        "photos_received_four": "Đã nhận 4 ảnh. Bây giờ hãy nhập mô tả (tối đa 1000 ký tự):",
        "done_to_text": "Xong (chuyển sang văn bản)",
        "enter_normal_text": "Bây giờ hãy nhập mô tả (tối đa 1000 ký tự):",
        "loc_car": "🚗 Bên xe",
        "loc_cafe": "☕ Tại quán cà phê",
        "loc_wall": "🧱 Bên tường",
        "loc_building": "🏢 Bên tòa nhà",
        "loc_moscow_city": "🏙️ Thành phố Moscow",
        "loc_forest": "🌲 Trong rừng",
        "loc_mountains": "⛰️ Trên núi",
        "loc_alley": "🛣️ Trên hẻm",
        "loc_park": "🌳 Trong công viên",
        "loc_city": "🏙️ Trong thành phố",
        "loc_studio": "📸 Studio ảnh",
        "loc_room": "🏠 Trong phòng",
        "loc_restaurant": "🍴 Trong nhà hàng",
        "loc_hotel": "🏨 Trong khách sạn",
        "loc_mall": "🛍️ Trong trung tâm thương mại",
        "admin_stats": "📊 Thống kê",
        "admin_users": "👥 Người dùng",
        "admin_search": "🔍 Tìm kiếm ID",
        "admin_models": "💃 Người mẫu",
        "admin_categories": "📂 Danh mục",
        "admin_own_prompts": "📝 Lời nhắc 'Thử riêng'",
        "admin_own_variant_prompts": "📝 Lời nhắc 'Biến thể riêng'",
        "admin_howto_edit": "ℹ️ Văn bản trợ giúp",
        "admin_api_keys": "🔑 Khóa API Gemini",
        "admin_own_variant_api_keys": "🔑 Khóa API 'Biến thể riêng'",
        "admin_logs": "📋 Nhật ký máy chủ",
        "admin_proxy": "🌐 Trạng thái Proxy",
        "admin_maint_on": "🛠 Bật bảo trì",
        "admin_maint_off": "✅ Tắt bảo trì",
        "admin_block": "⛔ Chặn",
        "admin_unblock": "✅ Bỏ chặn",
        "admin_list": "⤴️ Đến danh sách",
        "admin_title": "🛠 Bảng điều khiển",
        "admin_maint_status": "Bảo trì: {status}",
        "admin_user_title": "👤 Người dùng {uid}",
        "admin_user_status": "Trạng thái: {status}",
        "admin_history_no_tokens": "Lịch sử giao dịch không còn được hỗ trợ (đã xóa mã thông báo).",
        "admin_maint_enabled": "Đã bật",
        "admin_maint_disabled": "Đã tắt",
        "admin_panel_title": "🛠 Bảng điều khiển\nBảo trì: {status}",
        "admin_reset_usage": "Sử dụng: /reset_user <user_id>",
        "admin_reset_invalid": "Tham số không hợp lệ. Ví dụ: /reset_user 123456789",
        "admin_reset_success": "✅ Đã đặt lại trạng thái người dùng {user_id}",
        "admin_reset_error": "⚠️ Lỗi khi đặt lại trạng thái: {e}",
        "admin_stats_title": "📊 Thống kê",
        "admin_stats_total_users": "Tổng số người dùng",
        "admin_stats_today_users": "Mới hôm nay",
        "admin_stats_total_generations": "Tổng số lượt tạo",
        "admin_stats_today_generations": "Lượt tạo hôm nay",
        "admin_cats_edit": "Danh mục (nhấn để bật/tắt):",
        "admin_saved": "Đã lưu",
        "admin_prices_title": "💰 Giá danh mục (nhấn để chỉnh sửa):",
        "admin_enter_id": "Nhập ID người dùng (số):",
        "admin_enter_id_error": "Nhập ID dưới dạng số, ví dụ: 123456789",
        "admin_user_not_found": "Không tìm thấy người dùng",
        "admin_users_list": "👥 Người dùng:",
        "admin_models_title": "🧩 Người mẫu",
        "admin_maint_on_success": "Đã bật bảo trì",
        "admin_maint_off_success": "Đã tắt bảo trì",
        "admin_logs_getting": "Đang lấy nhật ký...",
        "admin_logs_parts": "📋 Nhật ký máy chủ gần nhất (phần {part}/{total}):",
        "admin_logs_error": "⚠️ Không thể lấy nhật ký tự động.",
        "admin_proxy_checking": "Đang kiểm tra proxy...",
        "admin_proxy_title": "🌐 Trạng thái proxy:",
        "admin_pick_cat": "Chọn một danh mục",
        "admin_pick_cloth": "Chọn loại quần áo",
        "admin_actions": "Hành động",
        "admin_model_num": "Người mẫu #{mid}",
        "admin_send_photo": "Gửi ảnh người mẫu (dưới dạng tin nhắn ảnh)",
        "admin_need_photo": "Cần gửi một bức ảnh",
        "admin_send_prompt": "Gửi lời nhắc cho người mẫu này (dưới dạng văn bản)",
        "admin_prompt_empty": "Lời nhắc không được để trống. Gửi văn bản lời nhắc hoặc tệp .txt.",
        "admin_send_name": "Nhập tên người mẫu (ví dụ: Người mẫu 1)",
        "admin_model_created": "Đã tạo người mẫu #{mid}",
        "admin_enter_prompt_title": "Nhập tiêu đề lời nhắc (dưới dạng tin nhắn).",
        "admin_enter_prompt_text": "Gửi văn bản lời nhắc.",
        "admin_prompt_created": "Đã tạo lời nhắc #{pid}",
        "admin_enter_new_name": "Nhập tên người mẫu mới dưới dạng tin nhắn",
        "admin_send_new_photo": "Gửi ảnh người mẫu mới (dưới dạng ảnh trong tin nhắn)",
        "admin_photo_updated": "Đã cập nhật ảnh cho người mẫu #{mid}",
        "admin_name_updated": "Đã cập nhật tên",
        "admin_pick_prompt": "Chọn một lời nhắc",
        "admin_deleted_return": "Đã xóa. Quay lại danh sách.",
        "admin_deleted": "Đã xóa",
        "admin_broadcast_done": "Đã hoàn thành gửi hàng loạt",
        "admin_broadcast_text_req": "Gửi văn bản để gửi hàng loạt (dưới dạng tin nhắn). Sau đó bạn có thể thêm ảnh hoặc bỏ qua.",
        "admin_broadcast_text_ok": "Đã nhận văn bản. Đính kèm hình ảnh (ảnh), video hoặc nhấn 'Bỏ qua'.",
        "admin_broadcast_preview": "Xem trước gửi hàng loạt:\n\n{text}",
        "admin_broadcast_cancel": "Đã hủy.",
        "admin_broadcast_success": "✅ Đã gửi hàng loạt",
        "admin_broadcast_error": "❌ Lỗi gửi: {e}",
        "admin_user_invalid": "Người dùng không hợp lệ",
        "admin_status_updated": "Đã cập nhật trạng thái",
        "admin_gemini_keys": "🔑 Khóa API Gemini:",
        "admin_gemini_add_key": "Gửi GEMINI_API_KEY mới (chuỗi). Sau đó chỉ định mức độ ưu tiên (số nguyên) hoặc /skip",
        "admin_gemini_add_key_own": "Gửi GEMINI_API_KEY mới cho 'Biến thể riêng' (chuỗi). Sau đó chỉ định mức độ ưu tiên (số nguyên) hoặc /skip",
        "admin_gemini_priority": "Chỉ định mức độ ưu tiên (số nguyên, càng cao thì độ ưu tiên càng cao) hoặc gửi /skip",
        "admin_gemini_key_added": "Đã thêm khóa",
        "admin_gemini_key_updated": "Đã cập nhật khóa",
        "admin_gemini_send_token": "Gửi mã thông báo mới (hoặc /skip để giữ mã cũ)",
        "admin_gemini_priority_req": "Chỉ định mức độ ưu tiên mới (số nguyên) hoặc /skip",
        "admin_own_variant_keys": "🔑 Khóa 'Biến thể riêng':",
        "admin_own_variant_prompt": "Lời nhắc 'Biến thể riêng':",
        "admin_own_variant_prompt_full": "📋 Lời nhắc 'Biến thể riêng' hiện tại:\n\n{text}",
        "admin_own_variant_prompt_none": "Chưa đặt lời nhắc 'Biến thể riêng'.",
        "admin_own_variant_prompt_edit_req": "Gửi lời nhắc mới (dưới dạng văn bản):",
        "admin_own_prompt_names": "Bước {idx}",
        "admin_logs_server": "📋 Nhật ký máy chủ gần nhất:",
        "admin_list_all": "📋 Liệt kê tất cả",
        "admin_add": "➕ Thêm",
        "admin_list": "📋 Danh sách",
        "admin_rename": "📝 Đổi tên",
        "admin_change_photo": "🖼 Thay đổi ảnh",
        "admin_change_prompt": "📝 Thay đổi lời nhắc",
        "admin_delete": "❌ Xóa",
        "admin_to_list": "Đến danh sách",
        "admin_add_key": "➕ Thêm khóa",
        "admin_cancel": "❌ Hủy",
        "admin_send": "🚀 Gửi",
        "admin_step_model": "Bước 1 (Người mẫu)",
        "admin_step_gen": "Bước 3 (Tạo)",
        "admin_view": "👁 Xem",
        "admin_edit": "📝 Chỉnh sửa",
        "admin_edit_btn": "📝 Chỉnh sửa",
        "admin_models_list": "Danh sách người mẫu",
        "agreement_not_set": "Chưa đặt thỏa thuận người dùng.",
        "admin_prices_edit_notice": "Trạng thái hiện tại của danh mục «{name}»: {status}\n\nBạn có thể thay đổi trạng thái danh mục trong bảng điều khiển tại g-box.space.",
        "admin_own_prompt_step1": "Bước 1 — Mô tả người mẫu",
        "admin_own_prompt_step2": "Bước 2 — (không sử dụng)",
        "admin_own_prompt_step3": "Bước 3 — Tạo cuối cùng",
        "admin_own_prompt_edit_req": "{name}: gửi văn bản lời nhắc (hoặc .txt)",
        "admin_price_empty": "Giá trống. Gửi một số hoặc số thập phân.",
        "admin_price_invalid": "Giá phải lớn hơn không.",
        "admin_price_format_error": "Định dạng giá không hợp lệ. Gửi một số hoặc số thập phân (ví dụ: 1, 1.2, 2.0).",
        "admin_txt_req": "Vui lòng gửi tệp .txt (văn bản/thuần túy) hoặc văn bản.",
        "admin_rebind_start": "Đang bắt đầu liên kết lại ảnh người mẫu... Việc này có thể mất chút thời gian.",
        "admin_rebind_no_token": "OLD_BOT_TOKEN chưa được đặt trong .env",
        "admin_rebind_done": "Xong. Đã cập nhật: {updated}, lỗi: {failed}.",
        "admin_gemini_key_val_error": "Ưu tiên không hợp lệ. Nhập một số nguyên hoặc /skip",
        "admin_gemini_token_empty": "Mã thông báo trống. Gửi chuỗi mã thông báo hoặc /skip",
        "admin_own_variant_key_show": "Khóa #{key_id}: {token}\nTrạng thái: {state_txt}",
        "admin_whitebg_notice": "Đối với danh mục này, chỉ thêm lời nhắc.",
    }
}

def get_string(key, lang="ru", **kwargs):
    text = STRINGS.get(lang, STRINGS["ru"]).get(key, STRINGS["ru"].get(key, key))
    if kwargs:
        try:
            return text.format(**kwargs)
        except (KeyError, IndexError, ValueError):
            return text
    return text
