STRINGS = {
    "ru": {
        "start_welcome": "Добро пожаловать в AI-ROOM! Выберите раздел:",
        "accept_terms": "Принять.",
        "subscribed": "Я подписался",
        "subscribe_channel": "Пожалуйста, подпишитесь на наш канал, чтобы использовать бота:",
        "menu_market": "Для маркетплейсов",
        "menu_profile": "Профиль",
        "menu_howto": "Инструкция",
        "menu_settings": "Настройки",
        "back_main": "⬅️ Назад в меню",
        "back": "⬅️ Назад",
        "lang_ru": "Русский",
        "lang_en": "English",
        "lang_vi": "Tiếng Việt",
        "select_lang": "Выберите язык:",
        "profile_info": "👤 Профиль\nID: {id}\nПодписка: {sub}\nОсталось генераций сегодня: {daily_rem}\n\nВыберите действие:",
        "sub_none": "Нет подписки",
        "sub_active": "{plan} (до {date})",
        "menu_subscription": "Подписка",
        "menu_history": "История генерации",
        "menu_referral": "Заработать с нами",
        "buy_plan": "Оформить подписку",
        "trial_info": "Вам доступен бесплатный пробный период: 1 день и 5 генераций!",
        "get_trial": "Получить пробный период",
        "marketplace_menu": "📦 Раздел для маркетплейсов:",
        "create_own_variant": "✨ Свой вариант (2 токена)",
        "upload_photo": "Загрузите фото (до 4-х штук). Отправьте их по одной или группой.",
        "enter_prompt": "Введите описание (до 1000 символов):",
        "select_format": "Выберите формат:",
        "history_title": "Последние 20 генераций:",
        "history_item": "PID: {pid}\nДата: {date}",
        "agreement": "Пользовательское соглашение",
        "how_to": "Как пользоваться ботом",
        "maintenance": "Ведутся технические работы. Пожалуйста, подождите.",
        "error_api": "Произошла ошибка при генерации. Попробуйте позже.",
        "rate_limit": "Слишком много запросов. Пожалуйста, подождите 20 секунд.",
    },
    "en": {
        "start_welcome": "Welcome to AI-ROOM! Choose a section:",
        "accept_terms": "Accept.",
        "subscribed": "I subscribed",
        "subscribe_channel": "Please subscribe to our channel to use the bot:",
        "menu_market": "For Marketplaces",
        "menu_profile": "Profile",
        "menu_howto": "Instructions",
        "menu_settings": "Settings",
        "back_main": "⬅️ Back to menu",
        "back": "⬅️ Back",
        "lang_ru": "Russian",
        "lang_en": "English",
        "lang_vi": "Vietnamese",
        "select_lang": "Choose language:",
        "profile_info": "👤 Profile\nID: {id}\nSubscription: {sub}\nGenerations left today: {daily_rem}\n\nChoose an action:",
        "sub_none": "No subscription",
        "sub_active": "{plan} (until {date})",
        "menu_subscription": "Subscription",
        "menu_history": "Generation History",
        "menu_referral": "Earn with us",
        "buy_plan": "Get Subscription",
        "trial_info": "Free trial available: 1 day and 5 generations!",
        "get_trial": "Get Free Trial",
        "marketplace_menu": "📦 Marketplace section:",
        "create_own_variant": "✨ Own variant (2 tokens)",
        "upload_photo": "Upload photos (up to 4). Send them one by one or as a group.",
        "enter_prompt": "Enter description (up to 1000 characters):",
        "select_format": "Select format:",
        "history_title": "Last 20 generations:",
        "history_item": "PID: {pid}\nDate: {date}",
        "agreement": "User Agreement",
        "how_to": "How to use the bot",
        "maintenance": "Maintenance in progress. Please wait.",
        "error_api": "An error occurred during generation. Please try again later.",
        "rate_limit": "Too many requests. Please wait 20 seconds.",
    },
    "vi": {
        "start_welcome": "Chào mừng đến với AI-ROOM! Chọn một mục:",
        "accept_terms": "Chấp nhận.",
        "subscribed": "Tôi đã đăng ký",
        "subscribe_channel": "Vui lòng đăng ký kênh của chúng tôi để sử dụng bot:",
        "menu_market": "Cho Sàn TMĐT",
        "menu_profile": "Hồ sơ",
        "menu_howto": "Hướng dẫn",
        "menu_settings": "Cài đặt",
        "back_main": "⬅️ Quay lại menu",
        "back": "⬅️ Quay lại",
        "lang_ru": "Tiếng Nga",
        "lang_en": "Tiếng Anh",
        "lang_vi": "Tiếng Việt",
        "select_lang": "Chọn ngôn ngữ:",
        "profile_info": "👤 Hồ sơ\nID: {id}\nGói đăng ký: {sub}\nSố lượt tạo còn lại hôm nay: {daily_rem}\n\nChọn một hành động:",
        "sub_none": "Chưa có gói đăng ký",
        "sub_active": "{plan} (đến {date})",
        "menu_subscription": "Gói đăng ký",
        "menu_history": "Lịch sử tạo",
        "menu_referral": "Kiếm tiền cùng chúng tôi",
        "buy_plan": "Đăng ký gói",
        "trial_info": "Dùng thử miễn phí: 1 ngày và 5 lượt tạo!",
        "get_trial": "Nhận dùng thử",
        "marketplace_menu": "📦 Mục dành cho Sàn TMĐT:",
        "create_own_variant": "✨ Biến thể riêng (2 xu)",
        "upload_photo": "Tải ảnh lên (tối đa 4 ảnh). Gửi từng ảnh hoặc gửi theo nhóm.",
        "enter_prompt": "Nhập mô tả (tối đa 1000 ký tự):",
        "select_format": "Chọn định dạng:",
        "history_title": "20 lượt tạo gần nhất:",
        "history_item": "PID: {pid}\nNgày: {date}",
        "agreement": "Thỏa thuận người dùng",
        "how_to": "Cách sử dụng bot",
        "maintenance": "Đang bảo trì. Vui lòng đợi.",
        "error_api": "Đã xảy ra lỗi khi tạo. Vui lòng thử lại sau.",
        "rate_limit": "Quá nhiều yêu cầu. Vui lòng đợi 20 giây.",
    }
}

def get_string(key, lang="ru", **kwargs):
    text = STRINGS.get(lang, STRINGS["ru"]).get(key, STRINGS["ru"].get(key, key))
    if kwargs:
        return text.format(**kwargs)
    return text

